---
###
###
### AS ALTERNATE CREATE/MODIFY THE `/etc/issue` FILE WITH CONTENT BASED ON ENV IN INV
- name: Set motd
  template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644